module.exports = {
  hacktues: {
    name: "HackTUES",
    shortDescription: "Автоматизиране и подобряване на учебния процес в ТУЕС",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_2: {
    name: "HackTUES 2",
    shortDescription: "Подпомагaне опазването на околната среда и социални каузи",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_3: {
    name: "HackTUES 3",
    shortDescription: "Art&&Creativity",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hack30xtues: {
    name: "Hack30xTUES",
    shortDescription: "Бизнес, училище, университетHackathon",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_365: {
    name: "HackTUES 365",
    shortDescription: "Полза на ежедневната работа на бизнеса и живота на хората",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_6: {
    name: "HackTUES 6",
    shortDescription: "Smart City",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_gg: {
    name: "HackTUES GG",
    shortDescription: "Develop for the environment",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_infinity: {
    name: "HackTUES Infinity",
    shortDescription: "Hackathon",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
  hacktues_soon: {
    name: "HackTUES Soon",
    shortDescription: "Hackathon",
    description: "Hackathon",
    date: "2019-02-22",
    location: "TUES",
    backgroundImg: "/assets/arc/hacktues/logo.png",
    logo: "/assets/arc/hacktues/logo.png",
    color: "#000000",
    link: "https://hacktues.com/",
    sponsors: [
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
      {
        name: "TUES",
        logo: "/assets/arc/hacktues/logo.png",
        link: "https://hacktues.com/",
      },
    ],
  },
};