import { ICard } from "../types/IArchive";

export const CARDS: ICard[] = [
  {
    id: 1,
    name: "HackTUES",
    shortDescription: "Автоматизиране и подобряване на учебния процес в ТУЕС",
    description: "Hackathon",
    date: "2015",
    location: "ТУЕС",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 2,
    name: "HackTUES 2",
    shortDescription:
      "Подпомагaне опазването на околната среда и социални каузи",
    description: "Hackathon",
    date: "2015",
    location: "ТУЕС",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-2",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 3,
    name: "HackTUES 3",
    shortDescription: "Art&&Creativity",
    description: "Hackathon",
    date: "2017",
    location: "ТУЕС",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-3",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 4,
    name: "Hack30xTUES",
    shortDescription: "Бизнес, училище, университет",
    description: "Hackathon",
    date: "2018",
    location: "ТУЕС",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-4",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 5,
    name: "HackTUES 365",
    shortDescription:
      "Полза на ежедневната работа на бизнеса и живота на хората",
    description: "Hackathon",
    date: "2019",
    location: "ТУЕС",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-5",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 6,
    name: "HackTUES 6",
    shortDescription: "Smart City",
    description: "Hackathon",
    date: "2020",
    location: "хибриден",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-6",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 7,
    name: "HackTUES GG",
    shortDescription: "Develop for the environment",
    description: "Hackathon",
    date: "2021",
    location: "онлайн",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-7",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 8,
    name: "HackTUES 8",
    shortDescription: "Space and beyond",
    description: "Hackathon",
    date: "2022",
    location: "онлайн",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-8",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 9,
    name: "Coming soon",
    shortDescription: "Coming soon",
    description: "Hackathon",
    date: "2023",
    location: "някъде",
    backgroundImg: "https://i.imgur.com/1ZQYQ2l.jpg",
    classNames: "hacktues-9",
    url: "https://hacktues.com/",
    sponsors: [],
  },
];
