import { ICard } from "../types/IArchive";

export const TITLE: string = "HackTUES 9";

export const METADATA = {
  title: TITLE,
  description:
    "Hack TUES е единственият хакатон в България, организиран от ученици за ученици.🙌 ",
  image: "https://hacktues.bg/logo.png",
  url: "https://hacktues.bg",
  twitter: "@hacktues",
  themeColor: "#000000",
  favicon: "/public/favicon.png",
  keywords: [
    "hackathon",
    "hacktues",
    "hacktues9",
    "hacktues8",
    "hacktues 9",
    "hacktues 8",
    "хакатон",
    "българия",
    "софия",
    "туес",
    "TUES",
    "ELSYS",
    "ТУЕС",
    "ЕЛСИС",
    "програмиране",
    "coding",
    "programming",
    "hack",
    "ученици",
    "студенти",
    "училище",
  ],
};

export const CARDS: ICard[] = [
  {
    id: 1,
    name: '<span>Hack</span><span style="color: rgb(68, 101, 118);">TUES</span>',
    shortDescription: "Автоматизиране и подобряване на учебния процес в ТУЕС",
    description: "Hackathon",
    date: "2015",
    location: "ТУЕС",
    backgroundImg: "/assets/arc/hacktues_5/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 2,
    name: '<span>Hack</span><span style="color: rgb(68, 101, 118);">TUES</span>&nbsp;<span>2</span>',
    shortDescription:
      "Подпомагaне опазването на околната среда и социални каузи",
    description: "Hackathon",
    date: "2015",
    location: "ТУЕС",
    backgroundImg: "/assets/arc/hacktues_5/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 3,
    name: '<span style="color: rgb(255, 255, 255);">Hack</span><span style="color: rgb(9, 192, 222);">TUES</span>&nbsp;<span style="color: rgb(178, 0, 110);">3</span>',
    shortDescription: "Art&&Creativity",
    description: "Hackathon",
    date: "2017",
    location: "ТУЕС",
    backgroundImg: "/assets/arc/hacktues_3/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 4,
    name: '<span style="color: cyan;">Hack<sup>30x</sup>TUES</span>',
    shortDescription: "Бизнес, училище, университет",
    description: "Hackathon",
    date: "2018",
    location: "ТУЕС",
    backgroundImg: "/assets/arc/hacktues_4/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 5,
    name: '<span style="color: white;">Hack</span><span style="color: rgb(153, 208, 43);">TUES</span><span style="color: rgb(153, 208, 43);"><sup>^365</sup></span>',
    shortDescription:
      "Полза на ежедневната работа на бизнеса и живота на хората",
    description: "Hackathon",
    date: "2019",
    location: "ТУЕС",
    backgroundImg: "/assets/arc/hacktues_5/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 6,
    name: '<span style="color: white;">Hack</span><span style="color: rgb(253, 173, 32);">TUES</span>&nbsp;<span style="color: white;">6</span>',
    shortDescription: "Smart City",
    description: "Hackathon",
    date: "2020",
    location: "хибриден",
    backgroundImg: "/assets/arc/hacktues_6/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 7,
    name: '<span style="color:#009d60">HackTUES</span>&nbsp;<span style="color:#105231">GG</span>',
    shortDescription: "Develop for the environment",
    description: "Hackathon",
    date: "2021",
    location: "онлайн",
    backgroundImg: "/assets/arc/hacktues_7/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 8,
    name: '<div style="display: flex; justify-content: end; align-items: end;"><span style="color:#EBCDDD">HackTUES</span>&nbsp;<span style="transform: rotate(90deg); color: #EBCDDD; self-align: end;">8</span></div>',
    shortDescription: "Space and beyond",
    description: "Hackathon",
    date: "2022",
    location: "онлайн",
    backgroundImg: "/assets/arc/hacktues_8/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
  {
    id: 9,
    name: "Coming soon",
    shortDescription: "Coming soon",
    description: "Hackathon",
    date: "2023",
    location: "някъде",
    backgroundImg: "/assets/arc/hacktues_5/cover.png",
    classNames: "hacktues-1",
    url: "https://hacktues.com/",
    sponsors: [],
  },
];
