export const REGULATION = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus in magna eget diam semper hendrerit. Donec sit amet placerat diam, in ullamcorper ipsum. Aenean vitae venenatis turpis. In mollis arcu eget mi efficitur faucibus. Sed euismod facilisis diam, tincidunt cursus elit venenatis eget. Nunc non suscipit leo, in suscipit magna. Nam sed posuere tellus. Maecenas consectetur neque sem, nec viverra eros consequat ut.

Sed quam sem, fermentum at odio sed, porttitor convallis ligula. Mauris quis tincidunt ipsum. Donec dolor ipsum, feugiat ut blandit eu, gravida eu erat. Quisque vitae feugiat libero. In luctus venenatis nisi, et finibus erat. Suspendisse tincidunt justo a dictum viverra. Fusce nisl ante, varius sit amet elit ac, fermentum interdum lorem. Morbi ornare justo vitae aliquam elementum. Integer gravida finibus nulla, sit amet ultricies mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus dui urna, aliquet at blandit ut, pretium sit amet quam.

Praesent tempor, sem sed pharetra placerat, mauris nibh vestibulum lorem, id dapibus mauris metus non nulla. Proin vehicula ex libero, eget mattis mauris consectetur quis. Nulla vel ullamcorper nulla. Ut interdum blandit dolor, et ultricies libero ultricies a. Aenean luctus quam non viverra feugiat. Aliquam interdum, magna a tincidunt pulvinar, augue arcu volutpat elit, faucibus semper metus eros quis arcu. In cursus aliquet elit, quis fringilla odio egestas sit amet. Nulla mollis nisl et aliquam venenatis. Praesent dignissim neque non eleifend sagittis. Ut porta turpis arcu, ac varius massa accumsan quis. Pellentesque viverra at odio quis semper. Ut quis metus id ante suscipit tristique. Nunc luctus pharetra nunc. Proin feugiat urna quis dui egestas, in dapibus mi eleifend. Sed pharetra pulvinar risus mollis bibendum. Nullam at enim lorem.

Vestibulum venenatis, orci sed lacinia posuere, orci arcu tempor nisi, ac rutrum libero tortor et orci. Aenean vel luctus ipsum. Quisque fermentum vulputate massa sed congue. Aliquam in libero enim. Ut diam orci, hendrerit non tellus ac, malesuada feugiat neque. Nunc ut mollis enim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum scelerisque tempor leo sit amet egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque nec consequat lorem.

Pellentesque dictum sapien fermentum, vehicula lectus et, semper augue. Curabitur efficitur vehicula ultrices. Vestibulum laoreet et justo vitae pellentesque. Phasellus ut hendrerit enim. Nulla ante nisi, pellentesque non commodo eu, congue ut libero. Vivamus ac finibus mi, et posuere nulla. Proin non augue tortor. Morbi malesuada, leo sed commodo fringilla, nisi neque volutpat nisl, ut sollicitudin dui ante non ligula. Nunc lobortis iaculis purus id dictum. Duis id tellus tortor. In hac habitasse platea dictumst. Nullam luctus maximus leo euismod accumsan. Ut sed tortor sit amet purus suscipit faucibus eu quis ex. Maecenas a varius ligula. Donec consequat tempus suscipit. Curabitur mattis tortor ac laoreet egestas.

Pellentesque mollis sodales convallis. Vestibulum fringilla diam sed augue placerat, vitae posuere ex dapibus. Fusce porta maximus erat vitae finibus. Proin lobortis lorem a diam molestie, eget maximus odio tristique. Phasellus malesuada felis et odio accumsan, nec sodales mauris dictum. Vivamus ex dolor, luctus eu erat ac, auctor feugiat lorem. Sed in tellus non sapien suscipit pulvinar eu ac nisl. Aliquam nec rhoncus lectus, sit amet sollicitudin felis.

Ut fermentum neque nulla, nec bibendum tortor rhoncus ac. Vivamus consectetur, quam eu malesuada imperdiet, magna enim tempus odio, ac vulputate nibh urna ac est. Nullam lacinia lacinia nulla eget eleifend. Sed lacus orci, malesuada eget mollis vitae, pellentesque ultrices nibh. Sed eleifend mauris in ex vestibulum, eget lacinia diam porttitor. Duis eu congue libero, sed suscipit neque. Vestibulum in mollis turpis, eget tincidunt urna. In est magna, rutrum luctus mollis vel, cursus sed felis. Praesent ut ligula euismod, ullamcorper orci non, vestibulum ipsum. Nunc ultrices erat hendrerit diam aliquet rutrum.

Vivamus sodales lobortis ultrices. Donec dapibus felis ac mi mattis rutrum. Sed porta elementum luctus. Integer iaculis turpis vitae lacinia finibus. Morbi a lobortis felis. Sed vel justo et nibh vulputate egestas. In ac mattis massa. Aenean iaculis scelerisque mollis.

Suspendisse dapibus in augue non venenatis. Morbi sit amet interdum nibh, at congue libero. Quisque tincidunt tincidunt ex nec laoreet. Sed erat libero, euismod scelerisque commodo vitae, tristique nec ex. Suspendisse potenti. Curabitur mattis diam tristique ex tristique congue. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Maecenas libero metus, ultrices at diam id, vehicula tempor ligula. Quisque mollis erat non tortor ultricies molestie. Duis nunc magna, pharetra non rutrum sit amet, finibus quis turpis. Sed justo eros, faucibus ac mauris vel, aliquet finibus justo. Aenean aliquet justo sed dui congue, vel facilisis nisl dignissim. Praesent vel aliquet nisl, quis molestie ligula. Nulla blandit turpis sit amet libero venenatis, eget rhoncus ipsum dictum. In elementum risus eu orci bibendum, sit amet dictum justo vulputate. Vestibulum condimentum massa in mauris imperdiet, et blandit velit laoreet. Donec laoreet laoreet efficitur.

Aenean cursus lobortis ipsum vitae elementum. Pellentesque faucibus lorem sed diam feugiat lacinia. Sed in dapibus odio, sed vehicula odio. Sed pellentesque porttitor sapien nec fringilla. Praesent vitae ante lectus. Ut lobortis fringilla arcu. Proin efficitur diam justo.

Morbi sagittis, nulla sit amet gravida sagittis, ligula est pellentesque quam, a facilisis lorem sapien ut erat. Aliquam varius nisi vel arcu tempus, eget sagittis velit ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus eleifend enim risus, eu ullamcorper ex consectetur a. Cras sed sapien et libero blandit posuere. Etiam lobortis dui ut sem pulvinar, nec ultricies tellus dapibus. Quisque nec aliquam libero, vel dapibus risus. Proin luctus sollicitudin vehicula. Nam laoreet, mauris vel dapibus elementum, dolor nunc finibus felis, ornare sagittis tortor nunc at neque.

Morbi eu rhoncus urna, vel cursus ipsum. Aliquam at metus non lectus sagittis interdum. Aenean sed augue et nibh condimentum maximus nec sit amet velit. Cras lacinia metus a velit dapibus, id vulputate lectus vestibulum. Nam vulputate tincidunt efficitur. Sed tempor porttitor metus mattis ullamcorper. Curabitur nec lorem odio. Cras dignissim libero sed felis congue, a convallis sapien sagittis. Nulla ut erat enim. Nam imperdiet ac eros sit amet luctus. Ut placerat arcu nunc. Mauris efficitur est quis justo laoreet maximus. Proin facilisis aliquet sapien, quis lacinia arcu vehicula vel. Vivamus a condimentum ipsum. Phasellus pulvinar eros id velit egestas, a porttitor orci tristique. In eleifend sem vitae enim eleifend, vitae eleifend leo congue.

Donec nec posuere magna. Etiam mauris ipsum, efficitur vestibulum iaculis sed, malesuada nec purus. Cras sed mi eu nisl rutrum pellentesque. Mauris ultrices justo quis dolor condimentum, et gravida metus ultricies. Maecenas dapibus sed odio a lacinia. Maecenas ac justo nunc. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla augue nisl, convallis dapibus tempus at, volutpat et nulla. Nullam porta velit nec libero consequat, quis tincidunt ligula aliquet. In ac erat malesuada, efficitur leo eu, ornare magna. Morbi at tristique mi. Praesent quis lectus suscipit, ultricies elit ut, feugiat ligula. Etiam eget justo neque.

Donec hendrerit orci id sem vestibulum tempus. Etiam tristique ligula velit, vitae molestie mi molestie et. Mauris accumsan eget augue eu faucibus. Morbi in dapibus dui, id volutpat sapien. Vestibulum in dignissim ipsum. Nulla orci neque, placerat nec orci eu, congue placerat nunc. Phasellus sodales at orci vel tincidunt. Suspendisse potenti. Curabitur maximus lobortis nisi. Etiam fermentum vehicula faucibus. Nunc id ante libero. Morbi in lacus suscipit, dictum est non, rhoncus ligula. Donec vel nulla vitae nunc mattis tempor vitae in quam. Curabitur non malesuada nisi. Nullam orci arcu, cursus eu risus ut, maximus porta purus.`;
