export const TECHNOLOGIES = [
  {
    name: "2D Art",
    icon: "2dart",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "3D Art",
    icon: "3dart",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "AngularJS",
    icon: "angularjs",
    backgroundColor: "#b52e31",
    color: "#ffffff",
  },
  {
    name: "Apache",
    icon: "apache",
    backgroundColor: "#d22128",
    color: "#ffffff",
  },
  {
    name: "Arduino",
    icon: "arduino",
    backgroundColor: "#00979d",
    color: "#ffffff",
  },
  {
    name: "Assembly",
    icon: "assembly",
    backgroundColor: "#6e4a7e",
    color: "#ffffff",
  },
  {
    name: "AWS",
    icon: "aws",
    backgroundColor: "#232f3e",
    color: "#ffffff",
  },
  {
    name: "Azure",
    icon: "azure",
    backgroundColor: "#0089d6",
    color: "#ffffff",
  },
  {
    name: "Babel",
    icon: "babel",
    backgroundColor: "#f9dc3e",
    color: "#000000",
  },
  {
    name: "Bash",
    icon: "bash",
    backgroundColor: "#4eaa25",
    color: "#ffffff",
  },
  {
    name: "Blender",
    icon: "blender",
    backgroundColor: "#f5792a",
    color: "#ffffff",
  },
  {
    name: "Blockchain",
    icon: "blockchain",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Bootstrap",
    icon: "bootstrap",
    backgroundColor: "#7952b3",
    color: "#ffffff",
  },
  {
    name: "C",
    icon: "c",
    backgroundColor: "#a8b9cc",
    color: "#000000",
  },
  {
    name: "C#",
    icon: "csharp",
    backgroundColor: "#239120",
    color: "#ffffff",
  },
  {
    name: "C++",
    icon: "cplusplus",
    backgroundColor: "#00599c",
    color: "#ffffff",
  },
  {
    name: "Cloud computing",
    icon: "cloudcomputing",
    backgroundColor: "#ff0000",
    color: "#ffffff",
  },
  {
    name: "CSS",
    icon: "css",
    backgroundColor: "#1572b6",
    color: "#ffffff",
  },
  {
    name: "Dart",
    icon: "dart",
    backgroundColor: "#0175c2",
    color: "#ffffff",
  },
  {
    name: "Django",
    icon: "django",
    backgroundColor: "#092e20",
    color: "#ffffff",
  },
  {
    name: "Docker",
    icon: "docker",
    backgroundColor: "#2496ed",
    color: "#ffffff",
  },
  {
    name: "Elexir",
    icon: "elexir",
    backgroundColor: "#6e4a7e",
    color: "#ffffff",
  },
  {
    name: "Emacs",
    icon: "emacs",
    backgroundColor: "#7f5ab6",
    color: "#ffffff",
  },
  {
    name: "Embedded",
    icon: "embedded",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "ESP32 / ESP8266",
    icon: "esp32",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "ExpressJS",
    icon: "expressjs",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Firebase",
    icon: "firebase",
    backgroundColor: "#ffca28",
    color: "#000000",
  },
  {
    name: "Flutter",
    icon: "flutter",
    backgroundColor: "#02569b",
    color: "#ffffff",
  },
  {
    name: "Git",
    icon: "git",
    backgroundColor: "#f05032",
    color: "#ffffff",
  },
  {
    name: "Golang",
    icon: "golang",
    backgroundColor: "#00acd7",
    color: "#ffffff",
  },
  {
    name: "Google Cloud",
    icon: "googlecloud",
    backgroundColor: "#4285f4",
    color: "#ffffff",
  },
  {
    name: "HangFire",
    icon: "hangfire",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "HTML",
    icon: "html",
    backgroundColor: "#e34f26",
    color: "#ffffff",
  },
  {
    name: "IBM cloud",
    icon: "ibmcloud",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "IoT",
    icon: "iot",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Java",
    icon: "java",
    backgroundColor: "#007396",
    color: "#ffffff",
  },
  {
    name: "JavaScript",
    icon: "javascript",
    backgroundColor: "#f7df1e",
    color: "#000000",
  },
  {
    name: "Jest",
    icon: "jest",
    backgroundColor: "#c21325",
    color: "#ffffff",
  },
  {
    name: "jQuery",
    icon: "jquery",
    backgroundColor: "#0769ad",
    color: "#ffffff",
  },
  {
    name: "Kotlin",
    icon: "kotlin",
    backgroundColor: "#0095d5",
    color: "#ffffff",
  },
  {
    name: "Kubernetes",
    icon: "kubernetes",
    backgroundColor: "#326ce5",
    color: "#ffffff",
  },
  {
    name: "Less",
    icon: "less",
    backgroundColor: "#1d365d",
    color: "#ffffff",
  },
  {
    name: "Linux",
    icon: "linux",
    backgroundColor: "#fCC624",
    color: "#000000",
  },
  {
    name: "MATLAB",
    icon: "matlab",
    backgroundColor: "#e16737",
    color: "#ffffff",
  },
  {
    name: "MicroPython",
    icon: "micropython",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "ML",
    icon: "ml",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Mobile Development",
    icon: "mobiledevelopment",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "MongoDB",
    icon: "mongodb",
    backgroundColor: "#47a248",
    color: "#ffffff",
  },
  {
    name: "MUI",
    icon: "materialui",
    backgroundColor: "#0081cb",
    color: "#ffffff",
  },
  {
    name: "MySQL",
    icon: "mysql",
    backgroundColor: "#4479a1",
    color: "#ffffff",
  },
  {
    name: "NextJS",
    icon: "nextjs",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Nginx",
    icon: "nginx",
    backgroundColor: "#269539",
    color: "#ffffff",
  },
  {
    name: "Node-RED",
    icon: "nodered",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "NodeJS",
    icon: "nodejs",
    backgroundColor: "#339933",
    color: "#ffffff",
  },
  {
    name: "NoSQL",
    icon: "nosql",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "OOPs",
    icon: "oops",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "PHP",
    icon: "php",
    backgroundColor: "#777bb4",
    color: "#ffffff",
  },
  {
    name: "PostgreSQL",
    icon: "postgresql",
    backgroundColor: "#336791",
    color: "#ffffff",
  },
  {
    name: "Python",
    icon: "python",
    backgroundColor: "#3776ab",
    color: "#ffffff",
  },
  {
    name: "Raspberry Pi",
    icon: "raspberrypi",
    backgroundColor: "#c51a4a",
    color: "#ffffff",
  },
  {
    name: "React Native",
    icon: "reactnative",
    backgroundColor: "#61dafb",
    color: "#000000",
  },
  {
    name: "ReactJS",
    icon: "reactjs",
    backgroundColor: "#61dafb",
    color: "#000000",
  },
  {
    name: "REST",
    icon: "rest",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Ruby",
    icon: "ruby",
    backgroundColor: "#cc342d",
    color: "#ffffff",
  },
  {
    name: "Ruby on Rails",
    icon: "rubyonrails",
    backgroundColor: "#cc0000",
    color: "#ffffff",
  },
  {
    name: "Rust",
    icon: "rust",
    backgroundColor: "#dea584",
    color: "#000000",
  },
  {
    name: "Sass",
    icon: "sass",
    backgroundColor: "#cc6699",
    color: "#ffffff",
  },
  {
    name: "Security",
    icon: "security",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Smart contracts",
    icon: "smartcontracts",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Solidity",
    icon: "solidity",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "SQL",
    icon: "sql",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Svelte",
    icon: "svelte",
    backgroundColor: "#ff3e00",
    color: "#ffffff",
  },
  {
    name: "Swift",
    icon: "swift",
    backgroundColor: "#ffac45",
    color: "#000000",
  },
  {
    name: "Tailwind",
    icon: "tailwind",
    backgroundColor: "#06b6d4",
    color: "#000000",
  },
  {
    name: "TensorFlow",
    icon: "tensorflow",
    backgroundColor: "#ff6f00",
    color: "#ffffff",
  },
  {
    name: "TypeScript",
    icon: "typescript",
    backgroundColor: "#3178c6",
    color: "#ffffff",
  },
  {
    name: "Unity3D",
    icon: "unity3d",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Unreal Engine",
    icon: "unrealengine",
    backgroundColor: "#313131",
    color: "#ffffff",
  },
  {
    name: "Vercel",
    icon: "vercel",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Vim",
    icon: "vim",
    backgroundColor: "#019733",
    color: "#ffffff",
  },
  {
    name: "Vite",
    icon: "vite",
    backgroundColor: "#646cff",
    color: "#ffffff",
  },
  {
    name: "VueJS",
    icon: "vuejs",
    backgroundColor: "#42b883",
    color: "#ffffff",
  },
  {
    name: "Web Development",
    icon: "webdevelopment",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Webpack",
    icon: "webpack",
    backgroundColor: "#8dd6f9",
    color: "#000000",
  },
  {
    name: "WordPress",
    icon: "wordpress",
    backgroundColor: "#21759b",
    color: "#ffffff",
  },
  {
    name: "Компютърни мрежи",
    icon: "networks",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
];
