export const TECHNOLOGIES = [
  {
    name: "React",
    icon: "react",
    backgroundColor: "#61dafb",
    color: "#000000",
  },
  {
    name: "Angular",
    icon: "angular",
    backgroundColor: "#dd0031",
    color: "#ffffff",
  },
  {
    name: "Vue",
    icon: "vuejs",
    backgroundColor: "#42b883",
    color: "#ffffff",
  },
  {
    name: "Node",
    icon: "nodejs",
    backgroundColor: "#339933",
    color: "#ffffff",
  },
  {
    name: "Express",
    icon: "express",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "MongoDB",
    icon: "mongodb",
    backgroundColor: "#47a248",
    color: "#ffffff",
  },
  {
    name: "MySQL",
    icon: "mysql",
    backgroundColor: "#4479a1",
    color: "#ffffff",
  },
  {
    name: "PostgreSQL",
    icon: "postgresql",
    backgroundColor: "#336791",
    color: "#ffffff",
  },
  {
    name: "Docker",
    icon: "docker",
    backgroundColor: "#2496ed",
    color: "#ffffff",
  },
  {
    name: "Kubernetes",
    icon: "kubernetes",
    backgroundColor: "#326ce5",
    color: "#ffffff",
  },
  {
    name: "AWS",
    icon: "amazonaws",
    backgroundColor: "#232f3e",
    color: "#ffffff",
  },
  {
    name: "Azure",
    icon: "azure",
    backgroundColor: "#0089d6",
    color: "#ffffff",
  },
  {
    name: "Google Cloud",
    icon: "googlecloud",
    backgroundColor: "#4285f4",
    color: "#ffffff",
  },
  {
    name: "Git",
    icon: "git",
    backgroundColor: "#f05032",
    color: "#ffffff",
  },
  {
    name: "C",
    icon: "c",
    backgroundColor: "#a8b9cc",
    color: "#000000",
  },
  {
    name: "C++",
    icon: "cplusplus",
    backgroundColor: "#00599c",
    color: "#ffffff",
  },
  {
    name: "C#",
    icon: "csharp",
    backgroundColor: "#239120",
    color: "#ffffff",
  },
  {
    name: "Java",
    icon: "java",
    backgroundColor: "#007396",
    color: "#ffffff",
  },
  {
    name: "Python",
    icon: "python",
    backgroundColor: "#3776ab",
    color: "#ffffff",
  },
  {
    name: "PHP",
    icon: "php",
    backgroundColor: "#777bb4",
    color: "#ffffff",
  },
  {
    name: "HTML",
    icon: "html5",
    backgroundColor: "#e34c26",
    color: "#ffffff",
  },
  {
    name: "CSS",
    icon: "css3",
    backgroundColor: "#264de4",
    color: "#ffffff",
  },
  {
    name: "JavaScript",
    icon: "javascript",
    backgroundColor: "#f7df1e",
    color: "#000000",
  },
  {
    name: "TypeScript",
    icon: "typescript",
    backgroundColor: "#3178c6",
    color: "#ffffff",
  },
  {
    name: "NoSQL",
    icon: "nosql",
    backgroundColor: "#e34c26",
    color: "#ffffff",
  },
  {
    name: "REST",
    icon: "rest",
    backgroundColor: "#6aa84f",
    color: "#ffffff",
  },
  {
    name: "Ruby",
    icon: "ruby",
    backgroundColor: "#cc342d",
    color: "#ffffff",
  },
  {
    name: "Ruby on Rails",
    icon: "rubyonrails",
    backgroundColor: "#cc0000",
    color: "#ffffff",
  },
  {
    name: "Swift",
    icon: "swift",
    backgroundColor: "#ffac45",
    color: "#000000",
  },
  {
    name: "Kotlin",
    icon: "kotlin",
    backgroundColor: "#0095d5",
    color: "#ffffff",
  },
  {
    name: "Go",
    icon: "go",
    backgroundColor: "#00add8",
    color: "#ffffff",
  },
  {
    name: "Rust",
    icon: "rust",
    backgroundColor: "#dea584",
    color: "#000000",
  },
  {
    name: "Elixir",
    icon: "elixir",
    backgroundColor: "#6e4a7e",
    color: "#ffffff",
  },
  {
    name: "Svelte",
    icon: "svelte",
    backgroundColor: "#ff3e00",
    color: "#ffffff",
  },
  {
    name: "Bash",
    icon: "bash",
    backgroundColor: "#4eaa25",
    color: "#ffffff",
  },
  {
    name: "Vim",
    icon: "vim",
    backgroundColor: "#019733",
    color: "#ffffff",
  },
  {
    name: "Linux",
    icon: "linux",
    backgroundColor: "#fCC624",
    color: "#000000",
  },
  {
    name: "TensorFlow",
    icon: "tensorflow",
    backgroundColor: "#ff6f00",
    color: '#ffffff'
  },
  {
    name: "Apache",
    icon: "apache",
    backgroundColor: "#d22128",
    color: "#ffffff",
  },
  {
    name: "Nginx",
    icon: "nginx",
    backgroundColor: "#269539",
    color: "#ffffff",
  },
  {
    name: "Deno",
    icon: "deno",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Next",
    icon: "next",
    backgroundColor: "#000000",
    color: "#ffffff",
  },
  {
    name: "Jest",
    con: "jest",
    backgroundColor: "#c21325",
    color: "#ffffff",
  },
  {
    name: "Dart",
    icon: "dart",
    backgroundColor: "#0175c2",
    color: "#ffffff",
  },
  {
    name: "Flutter",
    icon: "flutter",
    backgroundColor: "#02569b",
    color: "#ffffff",
  },
  {
    name: "Firebase",
    icon: "firebase",
    backgroundColor: "#ffca28",
    color: "#000000",
  },
  {
    name: "Vercel",
    icon: "vercel",
    backgroundColor: "#000000",
    color : "#ffffff"
  },
  {
    name: "Netlify",
    icon: "netlify",
    backgroundColor: "#00c7b7",
    color: "#ffffff",
  },
  {
    name: "Material UI",
    icon: "materialui",
    backgroundColor: "#0081cb",
    color: "#ffffff",
  },
  {
    name: "Tailwind",
    icon: "tailwind",
    backgroundColor: "#38b2ac",
    color: "#ffffff",
  },
  {
    name: "SASS",
    icon: "sass",
    backgroundColor: "#cc6699",
    color: "#ffffff",
  },
  {
    name: "Webpack",
    icon: "webpack",
    backgroundColor: "#8dd6f9",
    color: "#000000",
  },
  {
    name: "Babel",
    icon: "babel",
    backgroundColor: "#f9dc3e",
    color: "#000000",
  },
  {
    name: "JQuery",
    icon: "jquery",
    backgroundColor: "#0769ad",
    color: "#ffffff",
  },
  {
    name: "Bootstrap",
    icon: "bootstrap",
    backgroundColor: "#7952b3",
    color: "#ffffff",
  },
];
